from reportlab.lib.colors import HexColor
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch

from reportlab.platypus import (
    Paragraph,
    Spacer,
    PageBreak,
    Table,
    TableStyle
)


class CoverRenderer:
    """
    Renders the cover page of the Executive
    Intelligence Report.
    """

    # --------------------------------------------------
    # Styles
    # --------------------------------------------------

    title_style = ParagraphStyle(

        "CoverTitle",

        fontName="Helvetica-Bold",

        fontSize=28,

        leading=34,

        alignment=TA_CENTER,

        textColor=HexColor("#1E3A8A"),

        spaceAfter=18

    )

    subtitle_style = ParagraphStyle(

        "CoverSubtitle",

        fontName="Helvetica",

        fontSize=15,

        leading=20,

        alignment=TA_CENTER,

        textColor=HexColor("#64748B"),

        spaceAfter=40

    )

    company_style = ParagraphStyle(

        "Company",

        fontName="Helvetica-Bold",

        fontSize=34,

        alignment=TA_CENTER,

        textColor=HexColor("#2563EB"),

        spaceAfter=30

    )

    footer_style = ParagraphStyle(

        "Footer",

        fontName="Helvetica",

        fontSize=10,

        alignment=TA_CENTER,

        textColor=HexColor("#64748B")

    )

    metadata_style = ParagraphStyle(

        "Metadata",

        fontName="Helvetica",

        fontSize=11,

        leading=18,

        textColor=HexColor("#374151")

    )

    # --------------------------------------------------
    # Render
    # --------------------------------------------------

    @classmethod
    def render(
        cls,
        metadata
    ):

        story = []

        story.append(

            Spacer(
                1,
                0.7 * inch
            )

        )

        story.append(

            Paragraph(

                metadata.company,

                cls.company_style

            )

        )

        story.append(

            Paragraph(

                metadata.report_title,

                cls.title_style

            )

        )

        story.append(

            Paragraph(

                metadata.report_type,

                cls.subtitle_style

            )

        )

        table_data = [

            ["Generated By", metadata.generated_by],

            ["Generated On", metadata.generated_at],

            ["AI Model", metadata.ai_model],

            ["Version", metadata.version]

        ]

        table = Table(

            table_data,

            colWidths=[2.2 * inch, 3.6 * inch]

        )

        table.setStyle(

            TableStyle([

                (

                    "BACKGROUND",

                    (0, 0),

                    (0, -1),

                    HexColor("#2563EB")

                ),

                (

                    "TEXTCOLOR",

                    (0, 0),

                    (0, -1),

                    HexColor("#FFFFFF")

                ),

                (

                    "BACKGROUND",

                    (1, 0),

                    (1, -1),

                    HexColor("#F8FAFC")

                ),

                (

                    "GRID",

                    (0, 0),

                    (-1, -1),

                    0.5,

                    HexColor("#CBD5E1")

                ),

                (

                    "FONTNAME",

                    (0, 0),

                    (-1, -1),

                    "Helvetica"

                ),

                (

                    "BOTTOMPADDING",

                    (0, 0),

                    (-1, -1),

                    10

                ),

                (

                    "TOPPADDING",

                    (0, 0),

                    (-1, -1),

                    10

                ),

                (

                    "VALIGN",

                    (0, 0),

                    (-1, -1),

                    "MIDDLE"

                )

            ])

        )

        story.append(table)

        story.append(

            Spacer(

                1,

                2.8 * inch

            )

        )

        story.append(

            Paragraph(

                "Confidential • Generated by DemandIQ Executive Intelligence Engine",

                cls.footer_style

            )

        )

        story.append(

            PageBreak()

        )

        return story